"""
Validation Agent — Source verification + hallucination check

Input (from PipelineState):
  risk_report, top3_facilities, reason
  affected_material, affected_region, risk_type, severity
  affected_nodes, facility_data
  iteration (current retry count)

Output (written to PipelineState):
  valid        : bool
  failure_type : "minor" | "severe" | None
  issues       : list[str]
  iteration    : int  (incremented)

Retry routing (handled by LangGraph pipeline):
  minor  → re-run Synthesis Agent  (missing source, unverified entity)
  severe → re-run from Risk Assessment Agent  (wrong material, inconsistent classification)
  Max iterations: 2  (defined in state.MAX_VALIDATION_ITERATIONS)
"""

import os
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_groq import ChatGroq

from agents.llm_utils import invoke_json
from agents.state import (
    FailureType,
    MAX_VALIDATION_ITERATIONS,
    PipelineState,
)

load_dotenv(Path(__file__).parent.parent / ".env")

_llm: Optional[ChatGroq] = None


def _get_llm() -> ChatGroq:
    global _llm
    if _llm is None:
        _llm = ChatGroq(
            model="llama-3.1-8b-instant",
            api_key=os.environ["GROQ_API_KEY"],
            temperature=0,
            request_timeout=20,
            max_retries=1,
        )
    return _llm


# ── Deterministic checks ──────────────────────────────────────────────────────

def _deterministic_checks(state: PipelineState) -> list[str]:
    """
    Fast, rule-based checks that don't need an LLM.
    Returns a list of issue strings (empty = all passed).
    """
    issues: list[str] = []
    top3        = state.get("top3_facilities", [])
    report      = state.get("risk_report", "")
    af_material = state.get("affected_material", "").lower()
    affected_ids = {n["id"] for n in state.get("affected_nodes", [])}
    facility_data = state.get("facility_data", {})

    # 1. Top-3 facilities must exist in affected_nodes (NAATBatt-verifiable)
    for f in top3:
        if f["id"] not in affected_ids:
            issues.append(
                f"SEVERE: Facility '{f['company']}' (id={f['id']}) is not in the "
                f"affected_nodes list — not verifiable via NAATBatt."
            )

    # 2. Top-3 facilities must have facility_data (capacity data was retrieved)
    for f in top3:
        if f["id"] not in facility_data:
            issues.append(
                f"MINOR: No facility_data for '{f['company']}' (id={f['id']}) — "
                f"risk score may be unreliable."
            )

    # 3. Report must contain a source reference
    if "source:" not in report.lower() and "naatbatt" not in report.lower():
        issues.append(
            "MINOR: Risk report does not contain a source citation. "
            "Expected 'Source: NAATBatt facility data' or similar."
        )

    # 4. Affected material must appear in the report
    if af_material and af_material not in report.lower():
        issues.append(
            f"SEVERE: Affected material '{af_material}' does not appear in the risk report — "
            f"possible material misclassification."
        )

    return issues


# ── LLM checks ────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are the Validation Agent for a Battery Supply Chain Risk System.
Your job is to quality-check a risk report generated by the Synthesis Agent.

Check for:
1. CONSISTENCY — Does the risk_type and severity match the described event?
2. COHERENCE   — Is the reasoning in the report logically coherent?
3. HALLUCINATION — Does the report mention companies, facts, or figures not provided in the input data?
4. COMPLETENESS — Does each Top-3 facility entry have a specific justification and recommendation?

Respond ONLY with a JSON object — no explanation, no markdown, no code blocks.

JSON schema:
{
  "valid": true | false,
  "issues": ["<issue1>", "<issue2>", ...],
  "failure_type": null | "minor" | "severe"
}

Failure type rules:
- null   → report is valid (issues list must be empty)
- "minor"  → fixable by re-running Synthesis Agent (e.g. vague justification, missing recommendation)
- "severe" → requires re-running Risk Assessment Agent (wrong material, wrong risk_type, severity off by ≥2)
"""

USER_PROMPT_TEMPLATE = """Validate this risk report against the provided context.

CONTEXT:
- Risk type: {risk_type}
- Severity: {severity}/5
- Affected material: {affected_material}
- Affected region: {affected_region}
- Origin tier: {origin_tier}
- Assessment reason: {reason}

TOP 3 FACILITIES PROVIDED TO SYNTHESIS AGENT:
{top3_summary}

GENERATED RISK REPORT:
---
{risk_report}
---
"""


def _format_top3_summary(top3: list) -> str:
    lines = []
    for f in top3:
        lines.append(
            f"- {f['company']} | {f['segment']} | "
            f"score={f['risk_score_normalized']}/100 | "
            f"country={f['country']}"
        )
    return "\n".join(lines) if lines else "None"


# ── Main agent function ────────────────────────────────────────────────────────

def run_validation_agent(state: PipelineState) -> PipelineState:
    """
    LangGraph-compatible node function.
    Runs deterministic checks first, then LLM checks.
    Returns updated state with valid/failure_type/issues/iteration.
    """
    iteration = state.get("iteration", 0) + 1

    # The "no_seed_found" report (see synthesis_agent._no_seed_found_report) is a fixed,
    # non-generative notice — there's no risk claim, entity reference, or capacity figure
    # to validate. Judging it against normal-report expectations produces spurious
    # complaints (observed: "missing Top-3 justification") that would trigger a wasted
    # retry loop back to Risk Assessment Agent, which would just reproduce the same
    # no_seed_found result deterministically.
    if state.get("seed_generation_status") == "no_seed_found":
        return {
            **state,
            "valid":        True,
            "failure_type": None,
            "issues":       [],
            "iteration":    iteration,
        }

    # Hard stop: exceeded max iterations → accept report as-is with warning
    if iteration > MAX_VALIDATION_ITERATIONS:
        return {
            **state,
            "valid":        True,
            "failure_type": None,
            "issues":       ["Max iterations reached — report accepted with caveats."],
            "iteration":    iteration,
        }

    all_issues: list[str] = []

    # ── Step 1: deterministic checks ─────────────────────────────────────────
    det_issues = _deterministic_checks(state)
    all_issues.extend(det_issues)

    # ── Step 2: LLM checks ────────────────────────────────────────────────────
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=USER_PROMPT_TEMPLATE.format(
            risk_type        = state.get("risk_type", ""),
            severity         = state.get("severity", 3),
            affected_material= state.get("affected_material", ""),
            affected_region  = state.get("affected_region", ""),
            origin_tier      = state.get("origin_tier", ""),
            reason           = state.get("reason", ""),
            top3_summary     = _format_top3_summary(state.get("top3_facilities", [])),
            risk_report      = state.get("risk_report", ""),
        )),
    ]

    llm_result = invoke_json(_get_llm(), messages)
    llm_issues: list[str] = llm_result.get("issues", [])
    all_issues.extend(llm_issues)

    # ── Step 3: determine final validity and failure_type ─────────────────────
    # Deterministic SEVERE issues override LLM result
    has_severe = any("SEVERE" in i for i in all_issues)
    has_minor  = any("MINOR" in i for i in all_issues) or (
        not llm_result.get("valid", True) and llm_result.get("failure_type") == "minor"
    )

    if has_severe:
        failure_type: Optional[FailureType] = "severe"
        valid = False
    elif has_minor or not llm_result.get("valid", True):
        llm_ft = llm_result.get("failure_type")
        failure_type = llm_ft if llm_ft in ("minor", "severe") else "minor"
        valid = False
    else:
        failure_type = None
        valid = True

    return {
        **state,
        "valid":        valid,
        "failure_type": failure_type,
        "issues":       all_issues,
        "iteration":    iteration,
    }
